### PR TITLE
add FromJSON Datetime

### PR DESCRIPTION
**Pull request by tek**
any reason this was omitted?

### CODE REVIEW

**Comment by andrewthad** [comment]
I believe that the endOfInput parser is needed to ensure that datetimes with extraneous characters at the end are rejected.

Also, this PR commits to a space in the middle rather than the T that ISO8601 requires. I have seen both of these in the wild. I think it would be best for the I have seen both of these in the wild. I think it would be best for the fromjson instance to allow either of them.

**Comment by tek** [comment]
my reasoning was to just mirror the `ToJSON` instance – should we then support all possible formats? i.e. use `parser_lenient` and add the optional `T`?

**Comment by andrewthad** [comment]
Yeah, just support them all. In theory, having json encoding and decoding match is nice, but being generous decoding makes the instance much more useful for a user who is trying to use TH or generics to get a FromJSON instance for a data type with a lot of fields. All it takes is one field where the instance doesn't work right, and then you're back to writing it all out by hand. Either that or having to wrap the field in a newtype and pay syntactic overhead everywhere just to get a derived FromJSON instance.

Document that the FromJSON instance is lenient in the haddocks for it. That way, if it's very important for someone to decode datetimes strictly, at least the docs will make them aware of this.

**Comment by tek** [comment]
should all parsers get the added support for T instead of space?

**Comment by tek** [comment]
I see that the lenient parsers allow any character as a separator, so that should be solved!

**Comment by andrewthad** [comment]
This looks good. Are you ready for me to squash and merge?

**Comment by tek** [comment]
yes please!

**Pull request merged**
