### PR TITLE
Dmystuff

### PR DESCRIPTION
**Pull request by chessai**

### CODE REVIEW

**Comment by chessai** [comment]
I added nix stuff for my/others convenience, i understand if you don't want them in there. The parsers/builders i added are for Dmy stuff. Nothing I added conflicts with anything and builds succeed.

**Comment by andrewthad** [comment]
I'll merge this in the next hour. I'm in the middle of a big module restructuring for `chronos`, so I need to finish that before merging though.

**Comment by andrewthad** [comment]
@chessai I just merged a ton of breaking changes into master. Would you mind rebasing this to be on top of the new master? But don't actually try to use `git rebase` because `git` won't actually be able to handle it. Just make a new branch, copy your changes in, and PR that.

**Comment by chessai** [comment]
OK

**Pull request closed without merging**
