### PR TITLE
Drop support for GHCs earlier than 8.6

### PR DESCRIPTION
**Pull request by andrewthad**

### CODE REVIEW

**Review by chessai — APPROVED** [review]

**Comment by chessai** [comment]
Merge at will!

**Comment by andrewthad** [comment]
Dropping the old GHCs was just the beginning. I've got an `bytesmith` ISO-8601 datetime-offset parser that's been copied into at least four different applications and libraries that I'm going to pull in, and then there's an encoder targeting `ShortText` (and by extension, `Bytes`) as well. These should be a bit faster than the existing functions in this library, mostly because they only target ISO-8601 instead of trying to be flexible.

**Comment by andrewthad** [comment]
Performance improvement for decoding (about 2x) is shown by:

```
benchmarking parsing/Chronos.zeptoUtf8_YmdHMS
time                 193.6 ns   (192.3 ns .. 195.1 ns)
variance introduced by outliers: 17% (moderately inflated)

benchmarking parsing/Chronos.decodeShortTextIso8601
time                 89.38 ns   (88.91 ns .. 89.90 ns)
variance introduced by outliers: 14% (moderately inflated)
```

And for encoding (about 3x), we have:

```
benchmarking prettyPrint/YmdHMS/Chronos.builder_YmdHMS
time                 674.4 ns   (670.0 ns .. 679.6 ns)
variance introduced by outliers: 19% (moderately inflated)

benchmarking prettyPrint/ISO-8601-Zulu/Chronos.encodeShortTextIso8601Zulu
time                 194.9 ns   (192.5 ns .. 197.5 ns)
variance introduced by outliers: 37% (moderately inflated)
```

When interpreting this, keep in mind that the decode and encode functions from the `time` library are still an order of magnitude slower than even `chronos`'s slowest functions. For example, for parsing ISO-8601-encoded timestamps, `time` gives us:

```
benchmarking parsing/Time.parseTimeM
time                 8.575 μs   (8.517 μs .. 8.663 μs)
```

So, here we're talking about 89ns vs 8575ns, a two-order-of-magnitude performance gap.

In addition to the functions being faster, these changes make it possible to avoid needless conversion functions from `ByteString` to `ByteArray` when working with the `byteverse` universe. This saves a `memcpy`.

**Comment by chessai** [comment]
Epic

**Pull request merged**
