### PR TITLE
Support GHC 9.0.2 on Windows

### PR DESCRIPTION
**Pull request by chshersh**

### CODE REVIEW

**Comment by andrewthad** [comment]
Not sure what the AppVeyor build failures means:

```
src\Chronos.hs:862:74: error:
    * Couldn't match type: t0 [a0] -> [a0]
                     with: Language.Haskell.TH.Syntax.Q Language.Haskell.TH.Syntax.Exp
      Expected: Language.Haskell.TH.Lib.Internal.ExpQ
        Actual: t0 [a0] -> [a0]
    * Probable cause: `concat' is applied to too few arguments
      In the expression: concat
      In the untyped splice: $concat
src/Chronos/Locale/English.hs:25: failure in expression `import Chronos (january, august, december, october, caseMonth)'
expected: 
 but got: 
          ^
          <interactive>:1:1: error:
              attempting to use module `main:Chronos' (src\Chronos.hs) which is not loaded
src/Chronos.hs:357: failure in expression `deriving instance Arbitrary Time'
expected: 
 but got: 
          ^
          <interactive>:47:29: error:
              Not in scope: type constructor or class `Time'
Examples: 31  Tried: 9  Errors: 0  Failures: 2
```

**Comment by chshersh** [comment]
@andrewthad The CI seem to work now after I rebased on the latest `master` branch 👍🏻 
Is it possible to merge the PR and release the new version of `chronos` with the GHC 9.0 support? 🙏🏻

**Comment by andrewthad** [comment]
Merged. Also, see https://github.com/andrewthad/chronos/pull/73 where I have a release candidate for 1.1.4 which supports GHC 9.0.2 but not 9.2.1. If that looks good to you, I will merge and release it.

**Comment by chshersh** [comment]
@andrewthad Yep, this looks perfect 🔝 
GHC 9.2 support is not urgent to me so I'm happy with the current release 🤗

**Comment by NicolasT** [comment]
Looks like https://github.com/chshersh/chronos no longer exists (or not publicly, at least), and ref d16494c1df61023dab63d41d276c55f233ef887e doesn't exist in https://github.com/andrewthad/chronos, hence given the `cabal.project` file in this repository a simple `cabal build` fails.

**Pull request merged**
