### PR TITLE
[#42] Add Appveyor config

### LINKED ISSUE #42: Add Appveyor CI for Windows builds
Appveyor is free and working smoothly for Windows checks. We use it for @kowainik projects.
It doesn't take much effort to support, however, it could help to prevent situations with broken releases of `chronos`.

If you agree I can help with the config. As the reference, here how it would look like:

https://github.com/kowainik/summoner/blob/master/appveyor.yml

### PR DESCRIPTION
**Pull request by vrom911**
Resolves #42

This PR adds the config file. In order to actually turn on Appveyor for the repository you should actually sign in at appveyor.com and to add `chronos`. Here are the docs that should help: https://www.appveyor.com/docs/

Let me know if you have any questions or comments about this.

### CODE REVIEW

**Comment by chessai** [comment]
Awesome! I will do this when I get home tonight.

**Comment by chessai** [comment]
I lied. I will do this soon though. Thanks

**Comment by chessai** [comment]
Turns out the repo owner has to do it. So @andrewthad just merged.

**Comment by andrewthad** [comment]
There's a minor problem with doctest, but I'm working on that on https://github.com/andrewthad/chronos/pull/45.

**Comment by andrewthad** [comment]
Also, thanks @vrom911 for doing this! It's always nice to have things like this in place.

**Pull request merged**
