### PR TITLE
Try to make doctest work with appveyor

### PR DESCRIPTION
**Pull request by andrewthad**

### CODE REVIEW

**Comment by chessai** [comment]
```
Access violation in generated code when reading 0x8
 Attempting to reconstruct a stack trace...
   Frame	Code address
 * 0x3a2dd90	0x53cb9c C:\WORK\dist-newstyle\build\x86_64-windows\ghc-8.8.1\chronos-1.1\t\chronos-test\build\chronos-test\chronos-test.exe+0x13cb9c
```

this error is the same that we got from the `now` stuff when first implementing it for windows. what version of windows is this?

**Comment by chessai** [comment]
This might also be because of doctest? It's pretty opaque. But reminiscent of the `now` error.

**Comment by chessai** [comment]
@nprindle do you remember what the specific error with chronos windows' support was?

**Comment by chessai** [comment]
@nprindle nevermind, i was able to find it by searching our private messages

```
Access violation in generated code when reading 0x55a4818
```

but i could've sworn this was fixed

**Comment by vrom911** [comment]
@chessai, can you try to rerun that Appveyor build? The issue doesn't seem to be consistent as the `/branch` check passed without that error.

**Comment by chshersh** [comment]
I can recommend restarting `doctest` again. I see that tests pass, but the build hangs (it failed by time limit after 2 hours). This sometimes happens to me with `doctest` on AppVeyor. I'm not sure why (maybe some concurrency issue or GHC-specific bug on Windows). But restarting usually helps. Another possible reason — some specific test hangs on Windows. But as @vrom911 noticed, since tests are already passed, this is just unfortunate unstable behaviour.

**Comment by chessai** [comment]
I don't seem to have permissions to restart via AppVeyor itself. Perhaps @andrewthad can grant me them?

**Comment by andrewthad** [comment]
I've restarted the build. Also, I think I've now given permission to rebuild to anyone with write access to this repo, but that might not have worked, so let me know if you still can't rebuild.

**Comment by chessai** [comment]
Nice. Thanks

**Pull request merged**
